### ISSUE TITLE
M0 tree is not used

### ISSUE THREAD

**Issue by idavydov** [ssflows/fasty#6]
1) The tree used by codeml is identical to the tree used by fastcodeml.
The whole idea of running codeml with the model M0 (previously M1, see 1b5058e0e92ab76ae68405a22d37ae2aaae20719), was to get an input tree for codeml and not to optimize it in fastcodeml (see 598d4d7cb87c761d135ad38178a431c3d5400ffd).
Please provide the output tree of codeml as an input tree for the fastcodeml. It can be retrieved from the output file.
Also, the output file is traditionally named as something.mlc.
2) I suppose that's related. The output file of codeml is truncated.
I checked the output.out in the fastcodeml directory. It seems that the file is not full (i.e. there's no output tree in the file).

**Comment by anzaika** [comment]
I suppose truncation is somehow related to streaming std's realtime. Currently looking into it.
